USE [master]
GO

/****** Object:  Database [PatientDatabase]    Script Date: 10/23/2019 12:08:50 AM ******/
CREATE DATABASE [PatientDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientDatabase', FILENAME = N'F:\SQLSERVER2014\PatientDatabase.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PatientDatabase_log', FILENAME = N'F:\SQLSERVER2014\PatientDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatientDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatientDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PatientDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PatientDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PatientDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PatientDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [PatientDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PatientDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatientDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatientDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatientDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PatientDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PatientDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatientDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PatientDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatientDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PatientDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatientDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatientDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatientDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatientDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatientDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PatientDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatientDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PatientDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [PatientDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatientDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatientDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatientDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PatientDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatientDatabase] SET  READ_WRITE 
GO


